var searchData=
[
  ['set_5fthreads_5fper_5fblock_5fand_5fblocks_5fper_5fgrid',['set_threads_per_block_and_blocks_per_grid',['../class_generator_input_spiking_neurons.html#a77bc0da4313db248b03f6a6d51068598',1,'GeneratorInputSpikingNeurons::set_threads_per_block_and_blocks_per_grid()'],['../class_neurons.html#a892893f86b39367363551ae2dab16fc6',1,'Neurons::set_threads_per_block_and_blocks_per_grid()'],['../class_poisson_input_spiking_neurons.html#ab72f576d8d15b2a1f0f299ea09bc16c2',1,'PoissonInputSpikingNeurons::set_threads_per_block_and_blocks_per_grid()'],['../class_conductance_spiking_synapses.html#a5b039afee9f4712313419ee59b66bc72',1,'ConductanceSpikingSynapses::set_threads_per_block_and_blocks_per_grid()'],['../class_spiking_synapses.html#a55d9dba86e0bd6d3ca63444ea536f2ad',1,'SpikingSynapses::set_threads_per_block_and_blocks_per_grid()'],['../class_synapses.html#a58fb0ac86d547c25edb66f58600f6bde',1,'Synapses::set_threads_per_block_and_blocks_per_grid()']]],
  ['shuffle_5fsynapses',['shuffle_synapses',['../class_conductance_spiking_synapses.html#a2fa5c7da9449f23b5e1193a2a5cc3385',1,'ConductanceSpikingSynapses::shuffle_synapses()'],['../class_spiking_synapses.html#a3d51530ee79cf70ab497a3be556c42b8',1,'SpikingSynapses::shuffle_synapses()'],['../class_synapses.html#aa85d19a624beec4593946655986cfbe2',1,'Synapses::shuffle_synapses()']]],
  ['simulator',['Simulator',['../class_simulator.html',1,'']]],
  ['spikeanalyser',['SpikeAnalyser',['../class_spike_analyser.html',1,'']]],
  ['spikeplot',['SpikePlot',['../class_spike_plot_1_1_spike_plot.html',1,'SpikePlot']]],
  ['spiking_5fneuron_5fparameters_5fstruct',['spiking_neuron_parameters_struct',['../structspiking__neuron__parameters__struct.html',1,'']]],
  ['spiking_5fsynapse_5fparameters_5fstruct',['spiking_synapse_parameters_struct',['../structspiking__synapse__parameters__struct.html',1,'']]],
  ['spikingmodel',['SpikingModel',['../class_spiking_model.html',1,'']]],
  ['spikingneurons',['SpikingNeurons',['../class_spiking_neurons.html',1,'']]],
  ['spikingsynapses',['SpikingSynapses',['../class_spiking_synapses.html',1,'']]],
  ['start_5fneuron_5findices_5ffor_5feach_5fgroup',['start_neuron_indices_for_each_group',['../class_neurons.html#a310a29572deebca4b78169ae2915a5d1',1,'Neurons']]],
  ['stdp',['STDP',['../class_s_t_d_p.html',1,'']]],
  ['stdp_5fparameters_5fstruct',['stdp_parameters_struct',['../structstdp__parameters__struct.html',1,'']]],
  ['stimuli_5fpresentation_5fstruct',['Stimuli_Presentation_Struct',['../struct_stimuli___presentation___struct.html',1,'']]],
  ['synapse_5fparameters_5fstruct',['synapse_parameters_struct',['../structsynapse__parameters__struct.html',1,'']]],
  ['synapse_5fpostsynaptic_5fneuron_5fcount_5findex',['synapse_postsynaptic_neuron_count_index',['../class_synapses.html#a22de77b492ddcf90d24c6f1d82225ed0',1,'Synapses']]],
  ['synapses',['Synapses',['../class_synapses.html',1,'']]],
  ['synapses_2eh',['Synapses.h',['../_synapses_8h.html',1,'']]],
  ['synaptic_5fefficacies_5for_5fweights',['synaptic_efficacies_or_weights',['../class_synapses.html#a920d6ec78a3dc72ac811addf9e7311b0',1,'Synapses']]]
];
