#!/bin/sh

# script to create working directory, populate, and run text_book in serial.
# NOTE: if a real application is substituted for text_book it MUST BE SERIAL!

#-----------------------------------
# CREATE TEMPORARY WORKING DIRECTORY
#
# This prevents file trampling when running concurrent jobs.
#-----------------------------------



simulation_index=$(echo $1 | awk -F. '{print $NF}')

topdir=`pwd`
workdir=$topdir/workdir.$simulation_index
parameters_file_name=$1
results_file_name=$2

mkdir workdir.$simulation_index
cp $topdir/$parameters_file_name $workdir/dakota_vars
cp run_simulation_wrapper.pl workdir.$simulation_index/
cd $workdir
cp dakota_vars $parameters_file_name

./run_simulation_wrapper.pl $parameters_file_name $results_file_name $simulation_index
# use sleep command if file I/O timing is a problem
#sleep 10

cp $results_file_name ../$results_file_name

cd ..
